### ISSUE TITLE
happy_roberta predict_mask

### ISSUE THREAD

**Issue by liya-gafurova** [EricFillion/happy-transformer#173]
@ted537 , Hello! I Saw commit  https://github.com/EricFillion/happy-transformer/commit/0893d09645482998eda03d99326ec0d607eaeea8
Maybe it could cause a problem ...

I have an error: 
  File "/home/lia/PycharmProjects/venvs/nlp_venv/lib/python3.8/site-packages/happytransformer-1.1.4-py3.8.egg/happytransformer/happy_transformer.py", line 176, in predict_mask
    predictions = self.predict_masks(text, masks_options, num_results)
  File "/home/lia/PycharmProjects/venvs/nlp_venv/lib/python3.8/site-packages/happytransformer-1.1.4-py3.8.egg/happytransformer/happy_transformer.py", line 144, in predict_masks
    softmax = self._get_prediction_softmax(token_ids)
  File "/home/lia/PycharmProjects/venvs/nlp_venv/lib/python3.8/site-packages/happytransformer-1.1.4-py3.8.egg/happytransformer/happy_transformer.py", line 196, in _get_prediction_softmax
    return torch.softmax(outputs.logits[0], dim=-1)
AttributeError: 'tuple' object has no attribute 'logits'

while running: 
`happy_roberta.predict_mask(compiled_str, num_results=len(FULL_FORMS), options=FULL_FORMS))`

got an error here (class HappyTransformer._get_prediction_softmax) :
```
        with torch.no_grad():
            outputs = self.mlm(token_ids) # is  tensor [[]], with no logits
            return torch.softmax(outputs.logits[0], dim=-1)
```

Code was ok at the end of the last year

**Comment by ted537** [comment]
Could you send your `pip freeze` output?

**Comment by liya-gafurova** [comment]
Yes, sure
Here is a link to the file https://drive.google.com/file/d/1e2kXyTjSHF5x20uaIQsuuLFfbPBZ0owS/view?usp=sharing

Some notes:
- happytransformer installed from source (from zip) (for now I have installed working version - master branch state  BEFORE commit https://github.com/EricFillion/happy-transformer/commit/0893d09645482998eda03d99326ec0d607eaeea8)
- torch is 1.5.1
 - transformers==2.11.0
 - torch and transformers did NOT change their versions

Thank you in advance!

**Comment by ted537** [comment]
Yeah, sorry about that. We have been using a few features from newer releases of transformers. Upgrading transformers to at least 4.0.0 should resolve your issue.

This will be fixed in v2 as we'll have versioned dependencies.

Let us know if that works?

**Comment by liya-gafurova** [comment]
Yes, everything is working in v2.0
thank you!
